### ISSUE TITLE
Czytelność tekstu

### ISSUE THREAD

**Issue by oliwex** [EdutieProject/Dokumentacja#8]
Opisana dokumentacja jest napisana w sposób zbyt skomplikowany. Index FOG(index czytelności tekstu) wskazuje, że tekst jest napisany jak dla osób z wysokim wykształceniem.

Źródło: https://pl.wikipedia.org/wiki/Indeks_czytelno%C5%9Bci_FOG

**Comment by sukerberk1** [comment]
Solved: Niech osoby czytające nabędą wysokie wykształcenie
